Pattern

fig = px.chart_type(
    dataframe,
    x="column",
    y="column"
)

fig.show()

In [11]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [13]:
region_sales =(
    df_plotly.groupby('region', as_index= False)["sales"].sum()
)
region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [21]:
fig = px.bar(
    region_sales,
    x = "region",
    y = "sales",
    text = "sales",
    title= "Total sales by Region"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title= "Region",
    yaxis_title="Sales"
)

fig.show()

Interpretation

This chart helps answer:


Which region has the highest total sales?

Which region performs the weakest?

How large are the differences across regions?

In [24]:
monthly_sales = (
    df_plotly.groupby("month", as_index= False)["sales"].sum()
)
monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [29]:
fig = px.line(
    monthly_sales,
    x = "month",
    y = "sales",
    markers= True,
    title= "Monthly Total Sales"
)

fig.update_layout(
    xaxis_title = "Month",
    yaxis_title= "Sales"
)
fig.show()

Interpretation

This chart helps answer:

Is sales performance increasing or decreasing?

Which month had the highest sales?

Are there visible fluctuations over time?

In [34]:
fig = px.histogram(
    df_plotly,
    x = "sales",
    nbins= 15,
    title="Distribution of Sales"
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count"
)

fig.show()

Interpretation

This chart helps answer:

Are most sales values concentrated in one range?

Is the distribution symmetric or skewed?

Are there unusually small or large values?

In [38]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Customers vs Sales"
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

Interpretation

This chart helps answer:

Do higher customer counts tend to correspond to higher sales?

Are there outliers?

Do regions behave differently?

In [41]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
        .sum()
)

monthly_region_sales.head()

       month region  sales
0 2024-01-01   East    217
1 2024-01-01  North    276
2 2024-01-01  South    314
3 2024-02-01   East    273
4 2024-02-01  North    305

In [44]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

Interpretation
This chart helps answer:

Which region is strongest over time?

Which region is most volatile?

Do all regions move in the same direction?

In [46]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
            .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [48]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

Interpretation
This chart helps answer:

Which product performs better within each region?

Are some regions strong across both products?

Does one product dominate across all regions?

In [56]:
region_product_customers = (
    df_plotly.groupby(["region", "product"], as_index=False)["customers"]
            .sum()
)

region_product_customers

  region product  customers
0   East       A        321
1   East       B        293
2  North       A        292
3  North       B        313
4  South       A        367
5  South       B        306

In [58]:
fig = px.bar(
    region_product_customers,
    x="region",
    y="customers",
    color="product",
    barmode="group",
    text = "customers",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [62]:
fig = px.bar(
    region_product_sales,
    x="product",
    y="sales",
    color="region",
    barmode="group",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [63]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"].sum()
)

product_sales

  product  sales
0       A   2699
1       B   2334

In [69]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    hole=0.5,
    title="Share of Total Sales by Product"
)

fig.update_traces(textinfo="label+percent")

fig.show()

## COLORS

In [72]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence= ["#a34e31"]
)

fig.show()

In [73]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence= ["orange"]
)

fig.show()

In [75]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8"]
)

fig.show()

In [79]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_map={
        "A": "#3B6EAD",
        "B": "#AFC4E8"
    }
)

fig.show()

In [84]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales",
    color_discrete_sequence=["crimson"]
)

fig.show()

In [85]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region",
    color_discrete_sequence=["#1f77b4", "#ff7f0e", "#2ca02c"]
)

fig.show()

In [86]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales",
    color_discrete_sequence=["purple"]
)

fig.show()

In [87]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    title="Customers vs Sales",
    color_discrete_sequence=["darkorange"]
)

fig.show()

In [88]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    title="Customers vs Sales by Region",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8", "#B7C2D1"]
)

fig.show()

In [91]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region"
)

fig.update_traces(marker_color="teal")

fig.show()

In [100]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=[ "#ff7f0e", "#2ca02c"]
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [105]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_map={
        "A": "#3B6EAD",
        "B": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

## Highlighting Only the Specific Categories

In [111]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
        .sum()
)

top_region = region_sales.loc[region_sales["sales"].idxmax(), "region"]

region_sales["highlight"] = np.where(
    region_sales["region"] == top_region,
    "Highest Sales",
    "Other Regions"
)

region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800  Highest Sales
2  South   1674  Other Regions

In [119]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    color="highlight",
    text="sales",
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highest Sales": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

In [125]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
    .sum()
)

top_product = product_sales.loc[product_sales["sales"].idxmax(), "product"]

product_sales["highlight"] = np.where(
    product_sales["product"] == top_product,
    "Highest Sales",
    "Other Products"
)

product_sales

  product  sales       highlight
0       A   2699   Highest Sales
1       B   2334  Other Products

In [127]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    color="highlight",
    hole=0.5,
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highest Sales": "#3B6EAD",
        "Other Products": "#D9D9D9"
    }
)  

fig.update_traces(textinfo="label+percent")

fig.show()

In [129]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
    .sum()
)

max_month_row = monthly_sales.loc[monthly_sales["sales"].idxmax()]
max_month_row

month    2024-05-01 00:00:00
sales                    934
Name: 4, dtype: object

In [130]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Highlighting the Maximum Point"
)

fig.add_scatter(
    x=[max_month_row["month"]],
    y=[max_month_row["sales"]],
    mode="markers",
    marker=dict(size=14, color="#3B6EAD"),
    name="Maximum"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [135]:
avg_sales = monthly_sales["sales"].mean()
avg_sales

np.float64(838.8333333333334)

In [136]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot with Horizontal Reference Line"
)

fig.add_hline(
    y=avg_sales,
    line_dash="dash",
    annotation_text="Average Sales",
    annotation_position="top left"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [137]:
campaign_start = pd.Timestamp("2024-04-01")

fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot with Vertical Event Line"
)

fig.add_vline(
    x=campaign_start,
    line_dash="dot",
    line_color="red"
)

fig.add_annotation(
    x=campaign_start,
    y=monthly_sales["sales"].max(),
    text="Campaign Start",
    showarrow=True,
    arrowhead=2,
    ax=40,
    ay=-40
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [142]:
campaign_start = pd.Timestamp("2024-04-01")
avg_sales = monthly_sales["sales"].mean()

fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot with Horizontal and Vertical Reference Lines"
)

fig.add_hline(
    y=avg_sales,
    line_dash="dash",
    annotation_text="Average Sales",
    annotation_position="top left"
)

fig.add_vline(
    x=campaign_start,
    line_dash="dot",
    line_color="red"
)

fig.add_annotation(
    x=campaign_start,
    y=monthly_sales["sales"].max(),
    text="Campaign Start",
    showarrow=True,
    arrowhead=2,
    ax=40,
    ay=-40
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [161]:
campaign_start= pd.Timestamp("2024-03-01")
target_sales= monthly_sales["sales"].max()

fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers= True,
    title= "Line Plot with Horizontal and Vertical Reference Lines"
)
fig.add_vline(
    x=campaign_start,
    line_dash = "dot",
    line_color = "red",  
)

fig.add_annotation(
    x=campaign_start,
    y=monthly_sales["sales"].max(),
    text="Campaign Start",
    showarrow=True,
    arrowhead=2,
    ax=40,
    ay=-40
)

fig.show()